language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - hhvm

before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
 
script:
  - mkdir -p build/logs
  - phpunit tests/rapim_tests.php
  
matrix:
  fast_finish: true
  allow_failures:
      - php: hhvm
